### ISSUE TITLE
Set request headers/support non-shield authorization header?

### ISSUE THREAD

**Issue by bglusman** [werbitzky/elastix#13]
We're using elastic search on AWS which requires HMAC key signing as described here http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html

This elixir library implements it (https://github.com/bryanjos/aws_auth) nicely, but not sure best way to extend HTTP module to allow for auth other than shield.  Happy to contribute if I can (and may have to fork library just to add it, if I can't find a clean way to work around), but I'm just getting my feet wet, and not sure if you have a strong preference for how it be done.  Thanks!

**Comment by werbitzky** [comment]
Closing on account of #14
