### ISSUE TITLE
Timeout on HTTP Request

### ISSUE THREAD

**Issue by Florian95** [werbitzky/elastix#25]
Hi, 

On a very long search request, I quickly get : %HTTPoison.Error{id: nil, reason: :timeout}

How to setup the timeout ?

Regards and thank you for your work !

**Comment by werbitzky** [comment]
Yes, good point, I guess the timeout should be both *configurable globally* & *per request made*.

**Comment by X4lldux** [comment]
This can be achievable in current version (0.4.0), with:
```Elixir
config :elastix, 
  httpoison_options: [timeout: 60_000, recv_timeout: 60_000]
```

**Comment by werbitzky** [comment]
X4lldux, thanks! Closing..

**Comment by tslater** [comment]
Is there a way to do this per-request?
