### ISSUE TITLE
Throwing away errors

### ISSUE THREAD

**Issue by fredr** [werbitzky/elastix#26]
It would be nice to be able to pattern match on errors/ok, but it is not possible due to the error/ok atom being thrown away.

Example:
https://github.com/werbitzky/elastix/blob/master/lib/elastix/document.ex#L76

Wouldn't it be nicer to use the `{:ok, res}`  and `{:error, reason}`. Or is there any other reason why this is being stripped away?

**Comment by werbitzky** [comment]
Yes, you are right – this is not a good convention. Feel free to open a PR or I will change it for the next version.

**Comment by fredr** [comment]
Let me know what you think about that PR :clinking_glasses:
