### ISSUE TITLE
Custom Headers/AWS auth.

### ISSUE THREAD

**Issue by alanpeabody** [werbitzky/elastix#32]
The README describes supporting custom headers, however the same commit that adds that documentation seems to have actually removed support for custom headers. (https://github.com/werbitzky/elastix/commit/03daf52ff06206e4b0475cbed418470e336a3d60)

I would like to be able to use this library with elasticsearch on AWS and I am happy to contribute towards a solution.

Some ideas:

* Put back the custom header support, but make the API explicit (does it expect a module? function? what? - basically no misleading `.call()`). Maybe just a {Module, :fun, []} tuple that gets arguments prepended an applied. 
* Add an Elastix.HTTP.Authentication behaviour, which both shield and aws could implement. Could be configurable as `config :elastix, auth: Elastix.HTTP.Authentication.Shield`.

In the latter case AWS support could be added to this repo, added as a second hex package, or even just provide an example implementation in docs.

**Comment by alanpeabody** [comment]
@werbitzky any preference on this?

**Comment by werbitzky** [comment]
Hi @alanpeabody,

I would prefer to add custom header support, it would make the library more flexible in terms of not only authentication. Ideally adding custom headers should also be possible per call. Thank you for your contribution!

**Comment by alanpeabody** [comment]
Okay, I will get you something today. Thanks.

**Comment by werbitzky** [comment]
closing with pr https://github.com/werbitzky/elastix/pull/33
