### ISSUE TITLE
Document.index_new is producing the wrong url

### ISSUE THREAD

**Issue by walterbm** [werbitzky/elastix#38]
Calling `Document.index_new/4` or `Document.index_new/5` produces the wrong url because it appends a double backslash (e.g. `"/movies/movie//"`). This can cause problems with AWS authentication since it affects the request signature.

Seems like a minor fix so I would be glad to make a PR if needed.

**Comment by werbitzky** [comment]
@walterbm happy to get a PR from you! :)

**Comment by walterbm** [comment]
@werbitzky great! I created a PR #39 to fix the issue.

**Comment by werbitzky** [comment]
Fixed by https://github.com/werbitzky/elastix/pull/39
