### ISSUE TITLE
Support for bulk indexing

### ISSUE THREAD

**Issue by mrdziuban** [werbitzky/elastix#5]
Would it be possible to add support for bulk indexing documents, as described in the [Elasticsearch Bulk API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)? Thanks in advance!

**Comment by werbitzky** [comment]
yes, actually that should be pretty easy, I will add support as soon as I find time. :)

for now consider the following workaround:

```Elixir
    payload = create_bulk_payload(ordered_indexes)
        
    elastic_url = ShopApi.config :elastic_url
    index_name = ShopApi.config :elastic_index_name
    
    url = "#{elastic_url}/#{index_name}/_bulk"
    
    Elastix.HTTP.post(url, payload)
```

where ```payload``` would be a concatenated string of json indexing payloads, in bettween and ending with an \n

> the final line of data must end with a newline character \n.

**Comment by mrdziuban** [comment]
Awesome, thanks--that worked great! Feel free to close this if you want, or keep it open until the support is added

**Comment by werbitzky** [comment]
Closed thanks to @FabienHenon https://github.com/werbitzky/elastix/pull/23
