### ISSUE TITLE
Search multiple indices

### ISSUE THREAD

**Issue by norpan** [werbitzky/elastix#52]
I would like to be able to search multiple indices. I suggest the `search` function is extended so that the `index` parameter can be an array.

**Comment by norpan** [comment]
I found that you can just use "index1,index2" as the string passed, so no real need to fix this, although it would be a slightly nicer api if you could provide an array instead of having to create the comma-separated string yourself.

**Comment by Zinggi** [comment]
For anyone else coming here, you can also use '_all' to search all indexes:
https://www.elastic.co/guide/en/elasticsearch/reference/6.7/search-search.html
