### ISSUE TITLE
broken with latest version of HTTPoison

### ISSUE THREAD

**Issue by epilgrim** [werbitzky/elastix#53]
In the latest version (HTTPoison 1.4.0), they have introduced a Request struct
https://github.com/edgurgel/httpoison/pull/311
that makes the call here https://github.com/werbitzky/elastix/blob/master/lib/elastix/http.ex#L35 broken

**Comment by s4kibs4mi** [comment]
Facing the same issue.

**Comment by evuez** [comment]
I merged a fix for this into master, you can use `{:elastix, git: "https://github.com/werbitzky/elastix.git", branch: "master"}` in you mix deps until this is pushed on hex.pm
